services:

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: tasky
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password