spring.application.name=rereview

spring.elasticsearch.uris=http://localhost:9200

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9090/realms/rereview

app.storage.location=uploads

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB