spring.application.name=blogz

jwt.secret=TmFyMyAyRwvfhRW/A+cp8FO2dAec47alffDL7scn85k87IBj4QDTT6YFIChYt1Gq7r2JbsNJDdp+8J1JXOH5/g==

spring.datasource.url=jdbc:postgresql://localhost:5432/blogz
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
